### ISSUE TITLE
What's the license of the winform-image-gallery-Controls?

### ISSUE THREAD

**Issue by alanackart** [sm-abdullah/winform-image-gallery-Controls#1]
# Dear Sir, I want to know the exact license type of your controls. 
### Currently I am working on a project(a type tutor) for my course, and I want to publish the project I finished as an open source software in the next two months. so I wonder whether I can use your code in my open source project.

 
# I am looking forward for your early replay.

**Comment by sm-abdullah** [comment]
HI, off-course you can use. I have added license there which is MIT. Thanks.

**Comment by sm-abdullah** [comment]
You may like to visit this blog post about it, if not already.
http://www.codingsack.com/2016/01/03/accordion-image-slider-winform-control/

**Comment by alanackart** [comment]
Thanks! @sm-abdullah

**Comment by alanackart** [comment]
Thank for your reply. I am sorry to write to you so late for I does not check my Gmail regularly.
BTW, I am from Shanghai, China, glad to know a software developer from Pakistan.
